-- DONE
CREATE TABLE PRODUCT(
    id_product BIGINT SERIAL NOT NULL UNIQUE PRIMARY KEY,
    name_product VARCHAR(100) NOT NULL,
    license_term VARCHAR (50) NOT NULL,
    price INT CONSTRAINT positive_price CHECK (price > 0), CHECK (price < 50000),
    fk_category_id INT REFERENCES CATEGORY(id_category),
    fk_producer_id INT REFERENCES PRODUCER(id_producer),
);

--DONE
CREATE TABLE PRODUCT_BASKET_RELATION(
    id_product BIGINT NOT NULL,
    id_basket BIGINT NOT NULL,
    FOREIGN KEY (id_product) REFERENCES PRODUCT(id_product),
    FOREIGN KEY (id_basket) REFERENCES BASKET(id_basket),
    UNIQUE (id_basket, id_product)
);

-- ALSU
CREATE TABLE CATEGORY(
    id_category INT SERIAL NOT NULL UNIQUE PRIMARY KEY,
    name_category VARCHAR(100) NOT NULL
);

-- ALSU
CREATE TABLE UNIQUE_CODE(
    id_unique_code SERIAL NOT NULL UNIQUE PRIMARY KEY,
    id_product INT FOREIGN KEY REFERENCES PRODUCT(id_product),
    unique_code VARCHAR(100) UNIQUE NOT NULL
);

-- ALSU
CREATE TABLE COUNTRY(
    id SERIAL NOT NULL UNIQUE PRIMARY KEY,
    name_country VARCHAR(100) NOT NULL UNIQUE
);

-- LIYA
CREATE TABLE PRODUCER(
    id_producer SERIAL NOT NULL UNIQUE PRIMARY KEY,
);

-- LIYA
CREATE TABLE BASKET(
    id_basket SERIAL NOT NULL UNIQUE PRIMARY KEY,
);

-- LIYA
CREATE TABLE PROMOCODE(
    id SERIAL NOT NULL UNIQUE PRIMARY KEY,
);

-- AZALEA
CREATE TABLE PAYMENT(
    id SERIAL NOT NULL UNIQUE PRIMARY KEY,
);

-- AZALEA
CREATE TABLE ORDER(
    id SERIAL NOT NULL UNIQUE PRIMARY KEY,
);

-- AZALEA
CREATE TABLE CUSTOMER(
    id SERIAL NOT NULL UNIQUE PRIMARY KEY,
);