-- DONE
CREATE TABLE PRODUCT(
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    license_term VARCHAR (50) NOT NULL,
    price INT CONSTRAINT positive_price CHECK (price > 0), CHECK (price < 50000),
    category_id INT REFERENCES CATEGORY(id),
    producer_id INT REFERENCES PRODUCER(id),
);

--DONE
CREATE TABLE PRODUCT_BASKET_RELATION(
    product_id BIGINT NOT NULL REFERENCES PRODUCT(id),
    basket_id BIGINT NOT NULL REFERENCES BASKET(id),
    UNIQUE (basket_id, product_id) -- надо ли писать CONSTRAINT
);

-- ALSU
CREATE TABLE CATEGORY(
    id INT SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

-- ALSU
CREATE TABLE UNIQUE_CODE(
    id SERIAL PRIMARY KEY,
    id_product INT REFERENCES PRODUCT(id),
    unique_code VARCHAR(100) UNIQUE NOT NULL
);

-- ALSU
CREATE TABLE COUNTRY(
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

-- LIYA
CREATE TABLE PRODUCER(
    id SERIAL PRIMARY KEY,
);

-- LIYA
CREATE TABLE BASKET(
    id SERIAL PRIMARY KEY,

);

-- LIYA
CREATE TABLE PROMOCODE(
    id SERIAL PRIMARY KEY,
);

-- AZALEA
CREATE TABLE PAYMENT(
    id SERIAL PRIMARY KEY,
);

-- AZALEA
CREATE TABLE ORDER(
    id SERIAL PRIMARY KEY,
);

-- AZALEA
CREATE TABLE CUSTOMER(
    id SERIAL PRIMARY KEY,
);